datproject/datBase

browser/controllers/main.js, browser/index.js, browser/templates/metadat/publish.html, package.json
=> ENH: Enter button automatically advances forms in publish

api/indexer.js, browser/templates/main.html, browser/templates/pages/profile.html, browser/templates/pages/splash.html, index.html, static/styles/base.less, static/styles/includes/app.less, static/styles/includes/buttons.less, static/styles/includes/content.less, static/styles/includes/headers.less, static/styles/includes/responsive.less, static/styles/includes/variables.less, static/styles/pages/home.less
updating the front page for the beta release
=> style updates

index.html, src/js/app.js, src/js/components/hyperdrive-stats/index.js, src/js/components/index.js, src/scss/main.scss
Closes https://github.com/karissa/hyperdrive-ui/issues/34
=> show total upload and download

client/js/app.js, client/js/models/app-rehydrator.js, client/js/models/archive.js, client/js/models/user.js, package.json, server/page.js, server/router.js
=> dehydrate app state for server render, rehydrate on client 

client/js/app.js, client/js/components/header/index.js, client/js/models/help.js, server/page.js
=> Migrate help

client/js/components/header/index.js, client/js/elements/button/index.js, client/js/elements/import-button/index.js, client/scss/site-header.scss
this is pretty basic; just going to merge quickly. PR for posterity's sake.
=> de-couple import button from dat-header npm module

client/js/elements/hyperdrive-stats/index.js, client/js/models/archive.js, client/js/pages/archive/index.js
=> Migrate hyperdrive-stats.

client/js/elements/add-files/index.js, client/js/models/archive.js, client/js/pages/archive/index.js
Closes #166.
There's also stub import queue callbacks to be continued with #167.
=> migrate add-files

client/js/models/archive.js, client/js/pages/archive/index.js, client/js/pages/landing/index.js
Closes #185 (for the dat.land landing page part)
=> use chained actions to implement create archive + import files

client/js/components/hyperdrive/index.js, client/js/components/preview/index.js, client/js/models/archive.js, client/js/models/preview.js, package.json
rendering data in the browser using webrtc! At some point we might also want to change the URL so that people can link to a specific file inside the dat, but this PR doesn't include that feature. (should that be server-side or browser-side)?
=> Render data fixes #173

client/js/elements/hyperdrive-stats/index.js, client/js/models/archive.js, client/js/pages/archive/index.js
=> Migrate speed display

server/router.js
=> server render the metadata

client/js/components/hyperdrive/index.js, client/js/models/archive.js
=> Fix directories

client/js/models/archive.js
this flow will kick in when user is previewing a dat and then hits the "create new dat" button. the flow:
* resets the importQueue, removing active event listeners (in edge case where user is importing)
* !!! leaves previous archive swarm
* restores default state of archive model
=> reset archive model properly

server/router.js
=> reset entries

client/js/components/header/index.js, client/js/models/archive.js
=> just change route to '/' + key on import, forcing server render

client/js/components/display/index.js, client/js/components/preview/index.js, client/js/elements/404/index.js, client/js/models/preview.js
https://www.dropbox.com/s/gbt97yucl2ekmp4/magic.mov?dl=0
the root element for each item needed to be outside of `module.exports` so it never changes, but gets updated by the `render-data` module
=> fix the buggy preview screen

client/js/models/archive.js
=> bug: fix drag and drop on base route

.travis.yml, client/js/models/archive.js
=> Use local signalhub for e2e tests

client/js/components/display/index.js, client/js/models/archive.js
=> Sparse mode: preview now gets contents on demand.

client/js/models/archive.js
@laurengarcia this fixed the issue with the import queue not resetting in #269 ... defaultState seems to be getting mutated over the lifecycle of the app?
=> State reset

client/js/models/archive.js
=> bump import queue progress interval to 500ms

database/initial.sql
any fields we might be missing on a first pass?
=> add initial database file

client/js/elements/import-button/index.js
=> accept dat:// and dat.land links

package.json, server/index.js, server/router.js
uses bole for logging and adds structured error logging + logging for all requests
=> use ndjson for logging

client/js/pages/archive/index.js
=> make 'open in desktop' app button go to the github page

package.json, server/router.js
=> gzip assets ftw

.travis.yml, public/js/browser-warning.js
will not show the warning for firefox anymore
=> Firefox compat

client/js/app.js, client/js/components/header.js, client/js/components/login-button.js, client/js/pages/auth/login.js, server/router.js
=> Remove the login button and create /login page

client/js/components/display.js, client/js/components/preview.js, public/html/index.html
=> add message to download a client to get data

package.json, server/api/index.js, server/auth/index.js
Hi I'm just here with a couple small fixes for an embarrassing semver mistake I made with township/township. 😞
=> fix township mistake

example.config.js, package.json, server/entryStream.js, server/haus.js, server/index.js, server/router.js, tests/config.js, tests/helpers.js
this makes it a lot faster to fetch metadata
=> Add a leveldb metadata Cache

client/js/app.js, client/js/components/header.js, client/js/models/webrtc-archive.js, client/js/pages/create/index.js, public/html/splash.html, server/haus.js, server/router.js
=> Add dat route

tests/e2e/server.js
Reverts datproject/datproject.org#432
=> Revert "merge into beta"

client/js/pages/create/index.js
fixes a typo and the outdated "Desktop coming soon" on /install
=> fix outdated copy

package.json, server/router.js
* Adds middleware for permanent redirection links
* Redirects blog post for desktop app launch
=> redirect blog post for desktop launch

public/posts/2017-02-21-dat-desktop-is-here.md
Change to open.whitehouse.gov dataset.
=> update desktop blog post example

client/js/components/auth/register.js, client/js/components/header.js, client/js/components/login-button.js, client/js/models/user.js
=> add signup button to top right

client/js/components/auth/register.js, client/js/components/header.js, client/js/components/login-button.js, client/js/models/user.js
Reverts datproject/datproject.org#470
=> Revert "add signup button to top right"

public/html/splash.html
Links to https://github.com/datproject/dat-desktop/releases and says its experimental
=> Link to experimental linux build

client/js/app.js, client/js/components/auth/login.js, client/js/models/user.js, client/js/pages/auth/reset-password.js, server/auth/index.js, server/router.js
=> Password reset UI

public/posts/2017-03-08-berlin-hack-week.md
Review would be nice;
cc/ @juliangruber @Kriesse @mafintosh feel free to push anything you think's missing :sparkles:
=> Berlin hack week

client/js/pages/posts/2017-03-08-berlin-hack-week.md, client/js/pages/posts/index.js
Turns out I messed up a bunch of stuff with the previous post - this one works tho
=> fix issues with berlin post

client/js/models/user.js, server/errors.js, tests/e2e/user.js
=> Jwt expiration

client/js/components/copy-button.js, client/js/pages/archive/index.js, client/js/pages/archive/webrtc.js, client/scss/shared-imports/_base.scss, package.json, server/page.js
Cleans up markup to properly apply button styles, update to latest dat-icons. Fixes part of #490
=> fix styling of buttons with svg icons

client/js/components/display.js, client/js/elements/404/index.js, client/js/elements/icon/index.js, client/js/elements/loader-icon/index.js, client/js/elements/loading/index.js, client/js/pages/archive/webrtc.js, client/scss/shared-imports/_base.scss
add icon and loader components, show loading icon when loading, closes #490
=> show loader icon

client/js/pages/posts/2017-04-03.md
- add formatting to the screenshots so they don’t disappear in the background
- sprinkle in some single quotes and ellipsis
- fix link to release notes (https://github.com/datproject/datproject.org/releases/tag/1.02 @karissa please doublecheck)
=> Blog Post Style

client/js/models/read-only-archive.js
=> archive will have metadata updated when loaded

client/js/components/copy-button.js, package.json, tests/e2e/server.js
=> Make copy link work again

client/js/components/header.js, client/js/elements/404/index.js, client/js/pages/auth/reset-password.js, client/js/pages/create/index.js, client/js/pages/landing/blog.js, client/js/pages/landing/splash.js, client/scss/imports/_add-button.scss, client/scss/imports/_dat-header.scss, client/scss/shared-imports/_header-logo.scss, package.json
Also update dat-design. Closes #482.
=> Style reset password page

client/js/components/auth/login.js, client/js/components/auth/register.js, client/js/components/header.js, client/js/models/user.js, client/js/pages/auth/login.js, client/js/pages/auth/register.js, tests/e2e/user.js
=> make register/login pages not modals

client/js/app.js, client/js/components/display.js, client/js/components/hyperdrive/index.js, client/js/components/preview.js, client/js/models/preview.js, client/js/models/read-only-archive.js, client/js/pages/archive/index.js, server/router.js, tests/unit/api.js
It was pretty easy to do, so I went ahead and made it so that clicking on a file changes the URL so that file can be shared.
fixes #207 and #472 
Breaking changes:
* /:username/:dataset changed to ~/:username/dataset
* /dat/:archiveKey/:filename changed to /download/:archiveKey/:filename
=> Permanent file links

.gitignore, client/js/components/auth/login.js, client/js/components/auth/register.js, client/js/components/auth/user-panel.js, client/js/components/header.js, client/js/components/login-button.js, client/js/models/user.js, client/js/pages/auth/reset-password.js, client/js/pages/create/index.js, client/js/pages/landing/splash.js, client/scss/app.scss, client/scss/imports/_blog.scss, client/scss/imports/_dat-header.scss, client/scss/imports/_gravatar.scss, client/scss/imports/cli-tutorial.scss, client/scss/imports/gallery.scss, client/scss/shared-imports/_base.scss, client/scss/shared-imports/_grid.scss, client/scss/shared-imports/_header-logo.scss, client/scss/shared-imports/_layout.scss, client/scss/shared-imports/_sections.scss, client/scss/shared-imports/_site-header.scss, client/scss/shared-imports/_variables.scss
=> Add login register header 2

client/js/pages/download.js
=> update the download page to include desktop app

config/index.js, server/auth/verify.js, tests/e2e/user.js
=> set whitelist false, remove the whitelist test, add more bad names

server/auth/index.js, server/auth/reset.js, server/mailers/resetPassword.js
Add some light refactoring of the email system to prepare for email validation
=> Email refactor

client/js/models/archive.js, client/js/pages/archive/index.js, server/router.js
actually works and give a message when the number of retries has exceeded so
they know to refresh.
fixes #568
=> be smarter about fetching the archive page. make sure the loading screen

client/js/components/auth/login.js, client/js/components/auth/register.js, client/js/components/login-button.js
=> consistent language for logging in / registering

client/js/app.js, client/js/models/profile.js, client/js/pages/auth/delete-account.js, client/js/pages/auth/edit-profile.js, server/router.js, tests/e2e/user.js
=> add delete account page

package.json, server/router.js, tests/e2e/user.js
Use the latest version of dat-registry-api
=> Refactor db

client/js/elements/import-button/index.js, package.json
Rename placeholder to "Search Dat Link", use search icon.
Closes #584
=> Make purpose of search field more clear

README.md
default.js instead of config.default.js
=> fix filename in README

client/js/elements/import-button/index.js, client/js/models/archive.js, package.json, server/router.js, tests/e2e/server.js
fixes #592 
https://www.dropbox.com/s/h5st7facdmxkktr/boom.mov?dl=0
=> Allow users to search for a dat using the search bar

client/js/components/health.js, client/js/components/hyperdrive/client.js, client/js/components/hyperdrive/index.js, client/js/models/defaults.js
styling done, still needs data
=> [WIP] Show last modified time on archive page #521

client/js/pages/auth/reset-password.js, package.json
This requires choo v6 for state.query. We should probably wait until it becomes the released version.
=> Fix reset-password UI.

client/js/pages/landing/splash.js
i migrated them to a new server but i guess we lost the private at some points, hence the new links
=> update example dat links

client/js/models/township.js
Listen to township errors, so users can see registration errors.
Fixes #630, and provides more info for #629 hopefully!
=> listen to township errors
