datproject/datBase

package.json

made a breaking change to subleveldown in the way it handles sublevels in sublevels (it tried to be clever about it before - now it doesn't). might as well bump here now :)
remember to `npm install` afterward merging this

bump subleveldown

---

components/help/index.js
components/hyperdrive-size/index.js
components/hyperdrive-size/test.js
components/index.js
components/peers/index.js
components/reset-button/index.js
components/speed-display/index.js
index.html
index.js
package.json
static/style.css
store.js

So I found a great article that neatly explains why Minidux is a great tool for componentizing the app (Minidux is a pared down version of Redux):
https://css-tricks.com/learning-react-redux/
The basic idea is that we want a single source of truth for our app state that the components can dynamically subscribe to, rather than all the chaos of one component notifying another that something happened, and then the 2nd notifying a 3rd, and so and so on as commonly happens as browser apps complexify. Do read that article^^. Minidux is awesome and fixes this problem efficiently and effectively.
I went ahead and componentized the first few sample pieces that needed it, next week I (or someone else) can finish up so that the *only* logic in index.js (our app logic) is main() and getArchive() -- …

Componentize app with Minidux

---

package.json

This uses [yo-yoify](https://github.com/shama/yo-yoify) to transform the `yo-yo` templates into raw document calls. Making it compatible with browsers that dont support template strings, increases performance as it doesn't have to parse the templates and reduces the file size by removing bel/hyperx from the builds.
Thanks!

Use yo-yoify for perf and compat. Fixes GH-117

---

package.json
src/js/app.js

closes https://github.com/karissa/hyperdrive-ui/issues/56
followup issues are https://github.com/karissa/hyperdrive-ui/issues/49 and https://github.com/datproject/dat.land/issues/112

Use Sparse mode so files are downloaded individually

---

.gitignore
README.md
bin/git-sha.js
bin/version-assets.js
index.html
package.json
shipitfile.js

shipit is a lightweight capistrano. it has been tuned here to deploy to just the staging env for now. see readme and shipitfile.js for details.
note that the npm scripts have been rejiggered and you'll want to use `npm run dev` for development (where you would have used `npm start` before).

use shipit for 2-command deploys

---

client/js/app.js
client/js/components/hyperdrive/index.js
client/js/models/archive.js
server/haus.js
server/router.js

In irc:
```
@ogd> 
yoshuawuyts: does es2020 error if you use es2015+ language features that arent included in es2020? or does it just ignore them?
19:51 Y<yoshuawuyts> 
it ignores it as long as the parser is able to parse it
19:51 would be cool if we could make it fail tho, but that would probs require writing a bunch of babel plugins
19:52 O<@ogd> 
yoshuawuyts: gotcha. so its up to the user to make sure they only use the right features
19:53 Y<yoshuawuyts> 
yup
19:53 O<@ogd> 
clkao: so in that case we should just be careful to only use modern language features that are included in es2020 for now :D
```

 use 'var' instead of 'let' because of es2020 support on the node side

---

client/js/app.js
client/js/components/hyperdrive/index.js
client/js/components/preview/index.js
client/js/elements/button/index.js
client/js/models/archive.js
client/js/models/preview.js
client/js/pages/archive/index.js
client/scss/main.scss
client/scss/panel.scss
client/scss/preview-display.scss
client/scss/preview.scss

this should get @Kriesse moving forward with styling the preview panel.
to view the panel: only webrtc-to-webrtc peers are working at the moment, so you'll need to create a new archive via drag and drop in the ui. click on the resulting file name that gets rendered. panel will slide out. will continue this later but wanted to get styling moving forward.
relevant files: 
html can be modified in `client/js/components/preview`
scss in `scss/preview.scss`

single file preview panel

---

.gitignore
bin/version-assets.js
client/scss/main.scss
package.json
server/router.js

some updates/fixes here for production:
* fix broken build caused by removing the browserify transform here: https://github.com/datproject/dat.land/commit/fd2b004fa90b39697d2687ea08f32645557340b7
* now that the browserify build transform has been brought back, it needed to be switched from using `es2020` to `es2040` to support object destructuring syntax
* the css minifier was also borked up by a comment i added that was explaining how the scss magic importer worked (why was it looking at commented-out code tho?)
* closes #181 (updated the minification versioning script and set up a ?debug=true path in the router that returns the unminified resources for debugging)

Build fixes

---

.travis.yml
client/js/components/preview/index.js
client/js/models/archive.js

This was the forgotten item from dat.land roadmap for alpha. https://github.com/datproject/dat.land-roadmap/issues/32
We do need to do some kind of messaging for dat-cli-shared archives whose contents are not available. I'll open a separate issue around that because I'm not sure what the right user experience/messaging should be.

Download single archive file as zip

---

client/js/components/display/index.js

We really need to make sure that we are streaming in the data, this is one of the big benefits of dat is that we can stream in only say 10 rows of a 300gb csv (in theory ;p) without downloading the entire file first into memory.
This also has a placeholder for loading, telling the user that 'hey, im still looking to download this file but its taking a while to find a peer' which is a more accurate state for when it can't initially get the file metadata after 3 seconds. I'm sure we will continue to iterate on the loading language and add the new loading icons as soon we as we can get https://github.com/shama/bel/pull/31 merged.

Items in display should be streamed in

---

client/js/components/preview/index.js
client/js/models/archive.js
client/js/pages/archive/index.js
package.json

right now, when an cli-shared archive is not available for download as a zip, we don't do any messaging to the user. the user just clicks "download" and nothing happens. same for single file "download as zip" as well inside of the preview pane. this PR detects via the `archive.isEntryDownloaded()` method whether a file is available and pops up an alert message if not.

better messaging for unavailable single file .zip downloads

---

client/js/components/hyperdrive/client.js
client/js/components/hyperdrive/index.js
client/js/models/archive.js
package.json
server/components/hyperdrive/index.js

yo-fs used internally by hyperdrive-ui and choo were stepping on each other making it difficult.
Also this puts us more in control of where entries come from, because hyperdrive-ui does that for you.

Dont use hyperdrive ui

---

server/haus.js

the cache size of 100 might be a bit too big, running dat.land on a small machine now

reduce cache size in haus

---

client/js/components/hyperdrive/index.js

by returning false we bypass the error block: https://github.com/karissa/yo-fs/blob/master/index.js#L69

disable default behavior when using hyperdrive renderer. fixes #307

---

client/js/components/display/index.js
client/js/components/preview/index.js
client/js/elements/button/index.js
client/js/models/preview.js
client/js/pages/archive/index.js
client/scss/imports/_add-button.scss
client/scss/imports/_base.scss
client/scss/imports/_dat-header.scss

Disable the download button when archive is not downloadable. This uses `state.archive.numPeers`. It seems like that is the easiest way to tell if the archive is currently downloadable.
Other notes:
* Dims button to 50% opacity (to match icon)
* Had to add the disabled class to `btn__icon-wrapper`. Not ideal but couldn't see other ways to do it.
Yay front end!

Disable download button if there are no peers

---

client/js/components/auth/login.js
client/js/components/auth/register.js
client/scss/shared-imports/_base.scss

This implements modal styles that we already have in Dat Desktop. 
To Do: Re-use those styles instead of duplicating them in register and login. Probably by creating a modal element.

Style Account and Login UI

---

server/router.js
tests/unit/api.js

Adds the json response to datproject.org/user/dataset. 
Was having trouble with the old tests not passing. Can debug a bit later but it seemed like maybe related to township/appa change. 
TODO:

add json resp to root username/dat request

---

client/js/pages/landing/footer.js

datproject/datproject is not a valid github repository, and therefore will 404
when visited. This commit points the Github footer link to datproject/dat
instead, which seems like a logical place to me.

Fix broken footer link

---

client/js/models/read-only-archive.js
client/js/pages/archive/index.js
server/dats.js
server/router.js

fixes #323 
* Lowers the rendering timeout to 1s for archives, and replaces the 'no sources found' page with a loading page.
* Will ping for new updates to the archive info from the server every 3s (TODO: make this SSE/ws)
* **BONUS** Updates the filelist and metadata dynamically as its changed, too

Refresh server metadata

---

client/js/pages/archive/index.js
server/router.js

Now when the key is longer than 64 characters it will give you an accurate error message that the key is invalid, instead of saying 'Looking for sources...'  Also took the liberty to simplify the archive error handlers

simplify archive errors and make a better invalid key message

---

client/js/components/header.js
client/js/pages/archive/index.js
client/scss/imports/_dat-header.scss

better contrast, remove unnecessary truncation, only show permissions/size/peers when data exists

small style fixes
